# Generated by Django 6.1.1 on 2026-09-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quoterequestitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
    ]
