# Generated by Django 6.1.1 on 2026-09-12 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='public_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
