# Generated by Django 6.1.1 on 2026-09-12 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_quotation_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
